# Welcome to Jekyll!
#

# Site settings
title: SJA
description: |-
  Confía en nuestros abogados para una solución segura y sin preocupaciones. Realiza tus consultas sin costo.
owner: FTC # or company name
first_published: 2024 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "/ftc" # the subpath of your site, e.g. /blog
url: "https://enidev911.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  instagram: https://www.instagram.com/<username>
  email: mailto:example@mail.com
  # github: https://github.com/<username>
  # google-plus-square: https://plus.google.com/u/0/+<username>
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
